[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[plugin.inputs]
  enable_pnpm_support = true

[functions]
  included_files = ["**/*.css"] 